/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetomax.telas;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import projetomax.ProjetoMAX;
import projetomax.telas.modelos.UsuarioDataModel;
import projetomax.usuarios.ClienteCarnivoro;
import projetomax.usuarios.ClienteVegano;
import projetomax.usuarios.ClienteVegetariano;
import projetomax.usuarios.Nutricionista;
import projetomax.usuarios.Pessoa;

/**
 *
 * @author josel
 */
public class cadastroUsuario extends javax.swing.JFrame {

   private static ArrayList<Pessoa> pessoa = new ArrayList<>();
    /**
     * Creates new form cadastroCliente
     */
    public cadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void cadastraCliente(String nome, String descricao, String recceita, ArrayList<Pessoa> pessoa, int escolhaCliente){
        ClienteCarnivoro novoClienteC = new ClienteCarnivoro();
        ClienteVegano novoClienteV = new ClienteVegano();
        ClienteVegetariano novoClienteVe = new ClienteVegetariano();
        
        switch(escolhaCliente){
            case 1:
                novoClienteC.setNome(nome);
                novoClienteC.setDescricao(descricao);
                novoClienteC.setReceitaMedica(recceita);
                pessoa.add(novoClienteC);
                break;
            case 2:
                novoClienteC.setNome(nome);
                novoClienteV.setDescricao(descricao);
                novoClienteV.setReceitaMedica(recceita);
                pessoa.add(novoClienteV);
                break;
            case 3:
                novoClienteVe.setNome(nome);
                novoClienteVe.setDescricao(descricao);
                novoClienteVe.setReceitaMedica(recceita);
                pessoa.add(novoClienteVe);
                break;
        }
        
           
    }
        
    public void cadastraNutricionista(String nome, ArrayList<Pessoa> pessoa){
        Nutricionista cadastraNutri = new Nutricionista();
        cadastraNutri.setNome(nome);
        pessoa.add(cadastraNutri);
    }
    
    public void criaTabela(){
        UsuarioDataModel modelo = new UsuarioDataModel(pessoa);
        this.jTable1.setModel(modelo);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnCadastraCliente = new javax.swing.JButton();
        btnCancelaCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtDescCliente = new javax.swing.JTextField();
        txtReceitaCliente = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nome:");

        btnCadastraCliente.setText("Cadastra");
        btnCadastraCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraClienteActionPerformed(evt);
            }
        });

        btnCancelaCliente.setText("Cancela");

        jLabel2.setText("Descrição:");

        jLabel3.setText("Receita Médica:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "Cliente Carnívoro", "Cliente Vegetariano", "Cliente Vegano", "Nutricionista" }));
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtReceitaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelaCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastraCliente)))
                .addGap(38, 38, 38))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtReceitaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastraCliente)
                    .addComponent(btnCancelaCliente))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraClienteActionPerformed
        // TODO add your handling code here:
            cadastroUsuario novoCliente = new cadastroUsuario();
//            novo.setNome(txtNomeCliente.getText());
//            novo.setDescricao(txtDescCliente.getText());
//            novo.setReceitaMedica(txtReceitaCliente.getText());
            
            if(this.jComboBox1.getSelectedItem().equals("Nutricionista")){
                cadastraNutricionista(this.txtNomeCliente.getText(), pessoa);
                
                this.setVisible(false);
            }else if(this.jComboBox1.getSelectedItem().equals("Cliente Carnívoro")){
                novoCliente.cadastraCliente(txtNomeCliente.getText(), txtDescCliente.getText(),
                txtReceitaCliente.getText(), pessoa, 1);
                this.setVisible(false);
            }else if(this.jComboBox1.getSelectedItem().equals("Cliente Vegetariano")){
                novoCliente.cadastraCliente(txtNomeCliente.getText(), txtDescCliente.getText(),
                txtReceitaCliente.getText(), pessoa, 3);
                this.setVisible(false);
            }else if(this.jComboBox1.getSelectedItem().equals("Cliente Vegano")){
                novoCliente.cadastraCliente(txtNomeCliente.getText(), txtDescCliente.getText(),
                txtReceitaCliente.getText(), pessoa, 2);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "Selecione uma função");
            }
    }//GEN-LAST:event_btnCadastraClienteActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
//        this.txtDescCliente.setVisible(false);
//        this.txtReceitaCliente.setVisible(false);
//        this.jLabel2.setVisible(false);
//        this.jLabel3.setVisible(false);
this.setLocationRelativeTo(null);
criaTabela();

        
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
//        String escolhaCadastro = String.valueOf(this.jComboBox1.getSelectedItem());
//        if(escolhaCadastro.equalsIgnoreCase("<Selecione>")){
//                
//            }else if(escolhaCadastro.equalsIgnoreCase("Cliente Carnívoro")){
//                this.txtDescCliente.setVisible(true);
//                
//            }else if(escolhaCadastro.equalsIgnoreCase("Cliente Vegetariano")){
//                this.txtDescCliente.setVisible(true);
//                
//            }else if(escolhaCadastro.equalsIgnoreCase("Cliente Vegano")){
//                this.txtDescCliente.setVisible(true);
//                
//            }else{
//                
//            }
    }//GEN-LAST:event_formWindowActivated

    private void jComboBox1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeVisible
        // TODO add your handling code here:
//        if(jComboBox1.getSelectedItem().equals("<Selecione>")){
//                
//            }else if(jComboBox1.getSelectedItem().equals("Cliente Carnívoro")){
//                this.txtDescCliente.setVisible(true);
//                
//            }else if(jComboBox1.getSelectedItem().equals("Cliente Vegetariano")){
//                this.txtDescCliente.setVisible(true);
//                
//            }else if(jComboBox1.getSelectedItem().equals("Cliente Vegano")){
//                this.txtDescCliente.setVisible(true);
//                
//            }else{
//                
//            }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeVisible

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
          if(jComboBox1.getSelectedItem().equals("Nutricionista")){
                this.txtDescCliente.setVisible(false);
                this.txtReceitaCliente.setVisible(false);
                this.jLabel2.setVisible(false);
                this.jLabel3.setVisible(false);
//                this.btnExcluir.setVisible(true);
            }else if(jComboBox1.getSelectedItem().equals("Cliente Carnívoro")){
                this.txtDescCliente.setVisible(true);
                this.txtNomeCliente.setVisible(true);
                this.txtReceitaCliente.setVisible(true);
//                this.btnExcluir.setVisible(false);
                
            }else if(jComboBox1.getSelectedItem().equals("Cliente Vegetariano")){
                this.txtDescCliente.setVisible(true);
                this.txtNomeCliente.setVisible(true);
                this.txtReceitaCliente.setVisible(true);
//                this.btnExcluir.setVisible(false);
                
            }else if(jComboBox1.getSelectedItem().equals("Cliente Vegano")){
                this.txtDescCliente.setVisible(true);
                this.txtNomeCliente.setVisible(true);
                this.txtReceitaCliente.setVisible(true);
//                this.btnExcluir.setVisible(false);
                
            }else{
                
            }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_formWindowDeactivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastraCliente;
    private javax.swing.JButton btnCancelaCliente;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDescCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtReceitaCliente;
    // End of variables declaration//GEN-END:variables
    
}
